<a href="https://colab.research.google.com/github/parkmina365/OpenCV/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 데이터 분석과 이미지 처리
- 데이터 분석: 데이터를 수집하고, 분류하여 시각적으로 표현하는 과정
- 이미지 처리: 특정한 목적에 맞게 이미지를 가공하는 과정

# Numpy

## 1강. 행렬의 필요성
- 현실 세계의 많은 문제는 행렬을 이용해 쉽게 해결 가능
  - 배열(array)도 일종의 행렬
  - 데이터가 1개 이상이라면 행렬로 표현
- 행렬로 해결할 수 없다면 해결하기 매우 어려운 문제일 가능성
- 대부분의 연산은 행렬의 연산으로 표현 가능
  - 1차원 배열(벡터), 2차원 배열(행렬), 3차원 이상(텐서)
- 행렬이 중요한 이유?
  - 컴퓨터의 메모리 구조는 행렬 형태로 표현이 가능함
  - 2차원 형태로 표현되는 표 형태의 데이터는 행렬로 표현 될 수 있음
  - 이미지도 2차원이므로 행렬로 표현될 수 있음



## 2강. 다양한 파이썬 개발 환경 소개
- PyCharm
- Colab: OpenCV2
- Repl.it

## 3강. Numpy의 기본 사용법
- Numpy: 다차원 배열을 효과적으로 처리 할 수 있도록 도와주는 도구
  - 현실 세계의 다양한 데이터는 배열 형태로 표현 할 수 있음.
- 파이썬의 List와 호환되며, List보다 빠르고 강력한 기능 제공
- Numpy의 차원
  - 1차원 축(행): axis = 0, Vector
  - 2차원 축(열): axis = 1, Matrix
  - 3차원 축(채널): axis = 2, Tensor(3차원 이상)

In [ ]:
# List를 Numpy로 바꾸기
import numpy as np
array = np.array([1,2,3])
display([1,2,3], array, array.size, array.dtype, array[2])

# array는 size, dtype, index(기존 list와 동일)의 함수 제공

[1, 2, 3]

array([1, 2, 3])

3

dtype('int64')

3

In [ ]:
# Numpy 배열 만들기(초기화하기)
display(np.arange(4))
display(np.zeros((4,4),dtype=float))
display(np.ones((3,3), dtype=str))
display(np.random.randint(0,10,(3,3)))  # (0,10)사이 int의 랜덤한 배열
display(np.random.normal(0,1,(3,3)))    # 평균0, 표준편차 1인 정규분포의 랜덤한 배열

array([0, 1, 2, 3])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

array([[7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

array([[-0.38108715,  0.83083986,  1.61111963],
       [-0.98940129,  1.21104615,  1.07551655],
       [ 0.56927178, -0.20413855,  0.88357111]])

Numpy의 기본 사용법

In [ ]:
# Numpy 배열 합치기: np.concatenate
# 1차원
display(np.concatenate([np.array([1,2,3]), np.array([4,5,6])]))
display(np.concatenate([np.array([1,2,3]), np.array([4,5,6])]).shape)

# 2차원
display(np.concatenate([np.array([[1,2,3]]), np.array([[4,5,6]])]))
display(np.concatenate([np.array([[1,2,3]]), np.array([[4,5,6]])]).shape)

display(np.concatenate([np.array([[1,2,3]]), np.array([[4,5,6]])], axis=1))
display(np.concatenate([np.array([[1,2,3]]), np.array([[4,5,6]])], axis=1).shape)

array([1, 2, 3, 4, 5, 6])

(6,)

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)

array([[1, 2, 3, 4, 5, 6]])

(1, 6)

In [ ]:
# Numpy 배열 형태 바꾸기: .reshape
display(np.array([1,2,3,4]).reshape(2,2))
display(np.array([1,2,3,4]).reshape((2,2)))

# np.concatenate, reshape
display(np.concatenate([np.arange(4).reshape(1,4), np.arange(8).reshape(2,4)])) # defalut: axis=0(행방향)
display(np.concatenate([np.arange(4).reshape(1,4), np.arange(8).reshape(2,4)]).shape)

array([[1, 2],
       [3, 4]])

array([[1, 2],
       [3, 4]])

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

(3, 4)

In [ ]:
# Numpy 배열 나누기: np.split

left, right = np.split(np.arange(8).reshape(2,4), [2], axis=1) # 2번 열 기준으로 두개로 분리
display(np.arange(8).reshape(2,4), left, right, right[1][1])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[0, 1],
       [4, 5]])

array([[2, 3],
       [6, 7]])

7

## 4강. Numpy의 연산과 함수
- 상수(스칼라) 연산
- 배열간 연산
  - 배열의 형태가 같은 경우
  - 배열의 형태가 다른 경우
- 마스킹 연산: Boolean
  - Numpy 원소의 값을 조건에 따라 바꿀 때 사용
  - 반복문을 이용할 때보다 매우 빠르게 동작함
  - 이미지 처리(Image Processing)에서 자주 활용
- 집계 함수
  - np.min, np.max, np.sum, np.mean

In [ ]:
# 상수(스칼라) 연산
import numpy as np
display(np.arange(1,5)+2)
display(np.arange(1,5)*2)

array([3, 4, 5, 6])

array([2, 4, 6, 8])

In [ ]:
# 서로 다른 형태의 Numpy 연산
# 행 우선으로 수행됨

display(np.arange(4).reshape(2,2), np.arange(2))
np.arange(4).reshape(2,2) + np.arange(2)

array([[0, 1],
       [2, 3]])

array([0, 1])

array([[0, 2],
       [2, 4]])

In [ ]:
# 서로 다른 형태의 Numpy 연산
# Broadcast: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

array1 = np.concatenate([np.arange(0, 8).reshape(2, 4), np.arange(0, 8).reshape(2, 4)])
array2 = np.arange(0, 4).reshape(4, 1)
print(array1)
print(array1 + array2)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
# 마스킹 연산: 각 원소에 대해 T/F 여부 체크
# 원소의 값을 조건에 따라 바꿀수 있음
array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [ ]:
# 집계 함수
array = np.arange(16).reshape(4, 4)

print(array)
print("총 합계:", np.sum(array))
print("열 합계:", np.sum(array, axis=0))
print("행 합계:", np.sum(array, axis=1))
print("평균값:", np.mean(array))
print("최소값:", np.min(array))
print("최대값:", np.max(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
총 합계: 120
열 합계: [24 28 32 36]
행 합계: [ 6 22 38 54]
평균값: 7.5
최소값: 0
최대값: 15


## 5강. Numpy의 활용
- 저장, 불러오기: np.save, np.load
- 정렬: array.sort
- 함수
  - np.linspace
  - np.random.seed
  - array.copy
  - np.unique

In [ ]:
# Numpy의 저장과 불러오기: 단일 객체(.npy)

import numpy as np

array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Numpy의 저장과 불러오기: 복수 객체(.npz)

array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# Numpy 원소의 정렬

# 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

# 내림차순 정렬
array = array[::-1]
print(array)

# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [ ]:
# Numpy 함수

# 균일한 간격으로 데이터 생성: linspace
array = np.linspace(0, 10, 5) # range start, end, 총 간격수
print(array)

# 랜덤 씨드 고정: np.random.seed
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

# Numpy 배열 객체 복사: array.copy
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2)

# 중복된 원소 제거: np.unique
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
